channels:
  team:
    name: '<red><bold>@TEAM</bold></red>'
    # Note: The player needs to have the permission or simplechat.channel.* EXPLICITLY set!
    permission: simplechat.channel.team
    # Don't use spaces
    triggers:
      - '@team'
      - '@t'

prefer_user_metadata: true

chat:
  margin: "<dark_gray>»</dark_gray>"
  prefix_format: '<player_prefix><reset> <dark_gray>|</dark_gray> '
  suffix_format: ' <dark_gray>[</dark_gray><player_suffix><reset><dark_gray>]</dark_gray>'
  message_format: "<margin1><prefix_format><gray><player></gray><suffix_format> <dark_gray>»</dark_gray> <gray><message></gray><margin2>"
  channel_format: |- # You can use <name> (The chat's name), <player>, <message> and PlaceHolderAPI placeholders
    <dark_gray>»</dark_gray>
    <name> <dark_gray>|</dark_gray> <aqua><player></aqua> <dark_gray>»</dark_gray> <white><message>
    <dark_gray>»</dark_gray>
tab:
  default_color: gray
  prefix: "<player_prefix><reset> <dark_gray>|</dark_gray> "
  suffix: " <dark_gray>[</dark_gray><player_suffix><reset><dark_gray>]</dark_gray>"

  # To enable tab header and footer. Doesn't affect default_color, prefix or suffix.
  enabled: false
  # -1 to disable updating. Please only use this if you use placeholders which can change over time
  updateInterval: -1
  # This indicates the highest existing weight in your LuckPerms user/group prefixes.
  max_weight: 100

  header: |-
    ---> Servername <---
  footer: |-
    Tablist Footer
scoreboard:
  enabled: false
  # -1 to disable updating. Please only use this if you use placeholders which can change over time
  updateInterval: -1
  title: '  SERVERNAME  '
  scores:
    - ''
    - 'Score 1'
    - 'Score 2'
    - ''

emojis:
  - <3;❤
  - ":star:;§6✮§7"
  - ":yes:;§2✔§7"
  - ":no:;§c✖§7"
  - ":java:;§e☕§7"
  - ":arrow:;§e➜§7"
  - ":shrug:;§e¯\\_(ツ)_/¯§7"
  - ":tableflip:;§c(╯°□°）╯§f︵ ┻━┻§7"
  - "o/;§5( ﾟ◡ﾟ)/§7"
  - ":123:;§21§e2§c3§7"
  - ":totem:;§9◎§e_§9◎§7"
  - ":typing:;§e✎...§7"
  - ":maths:;§2√§e(§2π+x§e)§2=§c§lL§7"
  - ":snail:;§e@§2'§e-§2'§7"
  - ":thinking:;§6(§2O§6.§2o§c?§6)§7"
  - ":gimme:;§9༼つ ◕_◕ ༽つ§7"
  - ":wizard:;§e(§9'§e-§9'§e)⊃§c━§5☆ﾟ.*･｡ﾟ§7"
  - ":pvp:;§e⚔§7"
  - ":peace:;§e✌§7"
  - ":oof:;§c§lOOF§7"
  - ":puffer:;§e<('O')>§7"
  - ":snow:;§9☃§7"
  - ":dog:;§6(ᵔᴥᵔ)§7"
  - ":sloth:;§6( §8⬩ §6⊝ §8⬩ §6)§7"
  - ":dab:;§d<§eo§d/§7"
  - ":cat:;§e= §9＾● ⋏ ●＾ §e=§7"
  - ":yey:;§aヽ (◕◡◕) ﾉ§7"
  - "h/;§eヽ(^◇^*)/§7"
  - ":dj:;§9ヽ§d(⌐§c■§6_§e■§9)ノ♬§7"
  - ":cute:;§e(§a✿§eᴖ‿ᴖ)§7"