checkForUpdates: true

msg:
  chat:
    margin: "&8»"
    # The first %s is the playername and the second %s is the message. They can't be switched
    message: "<margin1><playerPrefix> §8| &7%s &8» &7%s<margin2>"
    teamChat: "&8»\n&c&l@TEAM &8| &b<player> &8» &f<message>\n&8»"
  tab:
    prefix: "<playerPrefix> &8| "
    color: "GRAY"
    suffix: " &8[<playerSuffix>&8]"

  listener:
    chatOff: '<prefix> Der Chat ist §bdeaktiviert!'
    enterText: '<prefix> §cBitte gib einen Text an!'

  command:
    chat:
      usage: '<cmd> <on|off>'
      alreadyOn: '<prefix> §cDer Chat ist bereits aktiviert!'
      alreadyOff: '<prefix> §cDer Chat ist bereits deaktiviert!'
      successOn: '<prefix> Der Chat wurde erfolgreich §baktiviert§7!'
      successOff: '<prefix> Der Chat wurde erfolgreich §bdeaktiviert§7!'
      announceOn: '<prefix> Der Chat wurde §baktiviert§7!'
      announceOff: '<prefix> Der Chat wurde §bdeaktiviert§7!'
    chatclear:
      console: Konsole
      success: '<prefix> Der Chat wurde gerade von §b<staff> §7gecleart!'
    emoji:
      activated: '&aaktiviert'
      deactivated: '&cdeaktiviert'
      success: '<prefix> Emojis sind nun <state>§7!'

preferUserMetaData: true
maxWeight: 100

emojis:
  - <3;❤
  - ":star:;§6✮§7"
  - ":yes:;§2✔§7"
  - ":no:;§c✖§7"
  - ":java:;§e☕§7"
  - ":arrow:;§e➜§7"
  - ":shrug:;§e¯\\_(ツ)_/¯§7"
  - ":tableflip:;§c(╯°□°）╯§f︵ ┻━┻§7"
  - "o/;§5( ﾟ◡ﾟ)/§7"
  - ":123:;§21§e2§c3§7"
  - ":totem:;§9◎§e_§9◎§7"
  - ":typing:;§e✎...§7"
  - ":maths:;§2√§e(§2π+x§e)§2=§c§lL§7"
  - ":snail:;§e@§2'§e-§2'§7"
  - ":thinking:;§6(§2O§6.§2o§c?§6)§7"
  - ":gimme:;§9༼つ ◕_◕ ༽つ§7"
  - ":wizard:;§e(§9'§e-§9'§e)⊃§c━§5☆ﾟ.*･｡ﾟ§7"
  - ":pvp:;§e⚔§7"
  - ":peace:;§e✌§7"
  - ":oof:;§c§lOOF§7"
  - ":puffer:;§e<('O')>§7"
  - ":snow:;§9☃§7"
  - ":dog:;§6(ᵔᴥᵔ)§7"
  - ":sloth:;§6( §8⬩ §6⊝ §8⬩ §6)§7"
  - ":dab:;§d<§eo§d/§7"
  - ":cat:;§e= §9＾● ⋏ ●＾ §e=§7"
  - ":yey:;§aヽ (◕◡◕) ﾉ§7"
  - "h/;§eヽ(^◇^*)/§7"
  - ":dj:;§9ヽ§d(⌐§c■§6_§e■§9)ノ♬§7"
  - ":cute:;§e(§a✿§eᴖ‿ᴖ)§7"