name: RyChat
version: '${project.version}'
main: com.rappytv.chat.RyChat
api-version: 1.20
authors: [ RappyTV ]
depend:
  - RyLib
  - LuckPerms
softdepend:
  - PlaceholderAPI

commands:
  chat:
    permission: rychat.manage
  chatclear:
    aliases: [ cc ]
    permission: rychat.clear
  emoji:
    aliases: [ emojis ]
    permission: rychat.emojis.toggle

permissions:
  rychat.manage.*:
    default: op
    children:
      rychat.manage:
        default: op
      rychat.manage.enable:
        default: op
      rychat.manage.disable:
        default: op
      rychat.manage.bypass:
        default: op
      rychat.reload:
        default: op

  rychat.clear:
    default: op
  rychat.clear.bypass:
    default: op

  rychat.name.black:
    default: false
  rychat.name.dark_blue:
    default: false
  rychat.name.dark_green:
    default: false
  rychat.name.dark_aqua:
    default: false
  rychat.name.dark_red:
    default: false
  rychat.name.dark_purple:
    default: false
  rychat.name.gold:
    default: false
  rychat.name.gray:
    default: false
  rychat.name.dark_gray:
    default: false
  rychat.name.blue:
    default: false
  rychat.name.green:
    default: false
  rychat.name.aqua:
    default: false
  rychat.name.red:
    default: false
  rychat.name.light_purple:
    default: false
  rychat.name.yellow:
    default: false
  rychat.name.white:
    default: false

  rychat.format.colors:
    default: op
  rychat.format.colors.hex:
    default: op
  rychat.format.bold:
    default: op
  rychat.format.italic:
    default: op
  rychat.format.underline:
    default: op
  rychat.format.strikethrough:
    default: op
  rychat.format.magic:
    default: op
  rychat.format.margin:
    default: op

  rychat.emojis:
    default: op
  rychat.emojis.toggle:
    default: op

  rychat.team:
    default: op