name: SimpleChat
version: '${project.version}'
main: com.rappytv.simplechat.SimpleChat
api-version: 1.21
authors: [ RappyTV ]
depend:
  - Sahara
  - LuckPerms
softdepend:
  - PlaceholderAPI

commands:
  chat:
    permission: simplechat.manage
  chatclear:
    aliases: [ cc ]
    permission: simplechat.clear
  emoji:
    aliases: [ emojis ]
    permission: simplechat.emojis.toggle

permissions:
  simplechat.manage.*:
    default: op
    children:
      simplechat.manage:
        default: op
      simplechat.manage.enable:
        default: op
      simplechat.manage.disable:
        default: op
      simplechat.manage.bypass:
        default: op
      simplechat.reload:
        default: op

  simplechat.chat.*:
    default: op
  simplechat.clear:
    default: op
  simplechat.clear.bypass:
    default: op

  simplechat.name.black:
    default: false
  simplechat.name.dark_blue:
    default: false
  simplechat.name.dark_green:
    default: false
  simplechat.name.dark_aqua:
    default: false
  simplechat.name.dark_red:
    default: false
  simplechat.name.dark_purple:
    default: false
  simplechat.name.gold:
    default: false
  simplechat.name.gray:
    default: false
  simplechat.name.dark_gray:
    default: false
  simplechat.name.blue:
    default: false
  simplechat.name.green:
    default: false
  simplechat.name.aqua:
    default: false
  simplechat.name.red:
    default: false
  simplechat.name.light_purple:
    default: false
  simplechat.name.yellow:
    default: false
  simplechat.name.white:
    default: false

  simplechat.format.colors:
    default: op
  simplechat.format.colors.hex:
    default: op
  simplechat.format.bold:
    default: op
  simplechat.format.italic:
    default: op
  simplechat.format.underline:
    default: op
  simplechat.format.strikethrough:
    default: op
  simplechat.format.magic:
    default: op
  simplechat.format.margin:
    default: op

  simplechat.emojis:
    default: op
  simplechat.emojis.toggle:
    default: op