name: Chat
version: '${project.version}'
main: com.rappytv.chat.ChatPlugin
api-version: 1.20
authors: [ RappyTV ]
depend:
  - RyLib
  - LuckPerms
softdepend:
  - PlaceholderAPI

commands:
  chat:
    permission: chat.manage
  chatclear:
    aliases: [ cc ]
    permission: chat.clear
  emoji:
    aliases: [ emojis ]
    permission: chat.emojis.toggle

permissions:
  chat.manage.*:
    default: op
    children:
      chat.manage:
        default: op
      chat.manage.enable:
        default: op
      chat.manage.disable:
        default: op
      chat.manage.bypass:
        default: op

  chat.clear:
    default: op
  chat.clear.bypass:
    default: op

  chat.name.black:
    default: false
  chat.name.dark_blue:
    default: false
  chat.name.dark_green:
    default: false
  chat.name.dark_aqua:
    default: false
  chat.name.dark_red:
    default: false
  chat.name.dark_purple:
    default: false
  chat.name.gold:
    default: false
  chat.name.gray:
    default: false
  chat.name.dark_gray:
    default: false
  chat.name.blue:
    default: false
  chat.name.green:
    default: false
  chat.name.aqua:
    default: false
  chat.name.red:
    default: false
  chat.name.light_purple:
    default: false
  chat.name.yellow:
    default: false
  chat.name.white:
    default: false

  chat.format.colors:
    default: op
  chat.format.colors.hex:
    default: op
  chat.format.bold:
    default: op
  chat.format.italic:
    default: op
  chat.format.underline:
    default: op
  chat.format.strikethrough:
    default: op
  chat.format.magic:
    default: op
  chat.format.margin:
    default: op

  chat.emojis:
    default: op
  chat.emojis.toggle:
    default: op

  chat.team:
    default: op