name: SimpleChat
version: '${project.version}'
main: com.rappytv.simplechat.SimpleChat
api-version: '1.21'
authors: [ RappyTV ]
depend:
  - Sahara
  - LuckPerms
softdepend:
  - PlaceholderAPI

commands:
  chat:
    permission: simplechat.manage.command
  chatclear:
    aliases: [ cc ]
    permission: simplechat.chat.manage.clear
  emoji:
    aliases: [ emojis ]
    permission: simplechat.emojis.toggle

permissions:
  simplechat.manage.*:
    default: op
    children:
      - simplechat.manage.chat.clear
      - simplechat.manage.chat.clear.bypass
      - simplechat.manage.chat.toggle
      - simplechat.manage.chat.toggle.bypass
      - simplechat.manage.command
      - simplechat.manage.reload

  simplechat.channel.*:
    default: op

  simplechat.chat.emojis:
    default: op
  simplechat.chat.emojis.toggle:
    default: op

  simplechat.chat.format.colors:
    default: op
  simplechat.chat.format.colors.hex:
    default: op
  simplechat.chat.format.bold:
    default: op
  simplechat.chat.format.italic:
    default: op
  simplechat.chat.format.underline:
    default: op
  simplechat.chat.format.strikethrough:
    default: op
  simplechat.chat.format.magic:
    default: op
  simplechat.chat.format.margin:
    default: op

  simplechat.chat.use:
    default: true

  simplechat.manage.chat.clear:
    default: op
  simplechat.manage.chat.clear.bypass:
    default: op
  simplechat.manage.chat.toggle:
    default: op
  simplechat.manage.chat.toggle.bypass:
    default: op
  simplechat.manage.command:
    default: op
  simplechat.manage.reload:
    default: op

  simplechat.name.black:
    default: false
  simplechat.name.dark_blue:
    default: false
  simplechat.name.dark_green:
    default: false
  simplechat.name.dark_aqua:
    default: false
  simplechat.name.dark_red:
    default: false
  simplechat.name.dark_purple:
    default: false
  simplechat.name.gold:
    default: false
  simplechat.name.gray:
    default: false
  simplechat.name.dark_gray:
    default: false
  simplechat.name.blue:
    default: false
  simplechat.name.green:
    default: false
  simplechat.name.aqua:
    default: false
  simplechat.name.red:
    default: false
  simplechat.name.light_purple:
    default: false
  simplechat.name.yellow:
    default: false
  simplechat.name.white:
    default: false